export const REGISTER_SHOPPER_REQUEST = 'REGISTER_SHOPPER_REQUEST';
export const REGISTER_SHOPPER_SUCCESS = 'REGISTER_SHOPPER_SUCCESS';
export const REGISTER_SHOPPER_FAILURE = 'REGISTER_SHOPPER_FAILURE';
export const REGISTER_SET_STEP = 'REGISTER_SET_STEP';
