export const FIND_ARTICLES_REQUEST = 'FIND_ARTICLES_REQUEST';
export const FIND_ARTICLES_SUCCESS = 'FIND_ARTICLES_SUCCESS';
export const FIND_ARTICLES_FAILURE = 'FIND_ARTICLES_FAILURE';
export const FIND_ARTICLE_REQUEST = 'FIND_ARTICLE_REQUEST';
export const FIND_ARTICLE_SUCCESS = 'FIND_ARTICLE_SUCCESS';
export const FIND_ARTICLE_FAILURE = 'FIND_ARTICLE_FAILURE';
